// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[slug]" | "/admin" | "/admin/banners" | "/admin/banners/[id]" | "/admin/banners/new" | "/admin/content" | "/admin/content/manage" | "/admin/login" | "/admin/media" | "/admin/media/manage" | "/admin/orders" | "/admin/orders/[id]" | "/admin/products" | "/admin/products/[id]" | "/admin/products/new" | "/admin/reviews" | "/admin/reviews/[id]" | "/admin/reviews/new" | "/admin/settings" | "/cart" | "/checkout/success" | "/collections/[slug]" | "/products/[slug]" | "/shop"
type AppRouteHandlerRoutes = "/api/admin/login" | "/api/admin/logout" | "/api/admin/media" | "/api/admin/media/upload" | "/api/admin/products/analyse-image" | "/api/catalog/collections" | "/api/catalog/products" | "/api/catalog/products-by-collection" | "/api/categories/[slug]" | "/api/checkout" | "/api/checkout/shiprocket-token" | "/api/home" | "/api/pages/[slug]" | "/api/products" | "/api/search" | "/api/webhooks/delivery-updates" | "/api/webhooks/shiprocket-checkout" | "/api/webhooks/shiprocket-shipping"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[slug]": { "slug": string; }
  "/admin": {}
  "/admin/banners": {}
  "/admin/banners/[id]": { "id": string; }
  "/admin/banners/new": {}
  "/admin/content": {}
  "/admin/content/manage": {}
  "/admin/login": {}
  "/admin/media": {}
  "/admin/media/manage": {}
  "/admin/orders": {}
  "/admin/orders/[id]": { "id": string; }
  "/admin/products": {}
  "/admin/products/[id]": { "id": string; }
  "/admin/products/new": {}
  "/admin/reviews": {}
  "/admin/reviews/[id]": { "id": string; }
  "/admin/reviews/new": {}
  "/admin/settings": {}
  "/api/admin/login": {}
  "/api/admin/logout": {}
  "/api/admin/media": {}
  "/api/admin/media/upload": {}
  "/api/admin/products/analyse-image": {}
  "/api/catalog/collections": {}
  "/api/catalog/products": {}
  "/api/catalog/products-by-collection": {}
  "/api/categories/[slug]": { "slug": string; }
  "/api/checkout": {}
  "/api/checkout/shiprocket-token": {}
  "/api/home": {}
  "/api/pages/[slug]": { "slug": string; }
  "/api/products": {}
  "/api/search": {}
  "/api/webhooks/delivery-updates": {}
  "/api/webhooks/shiprocket-checkout": {}
  "/api/webhooks/shiprocket-shipping": {}
  "/cart": {}
  "/checkout/success": {}
  "/collections/[slug]": { "slug": string; }
  "/products/[slug]": { "slug": string; }
  "/shop": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
